{{- if not (empty $.Values.envVarsFromSsm) }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ $.Values.appName }}
  labels:
    app: {{ $.Values.appName }}
spec:
  backendType: systemManager
  data:
    {{- range $envVar, $ssmPath := $.Values.envVarsFromSsm }}
    {{- if not (empty $ssmPath) }}
    - key: {{ $ssmPath }}
      name:  {{ $envVar }}
    {{- end }}
    {{- end }}
{{- end }}