{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.appName }}
  labels:
    app: {{ $.Values.appName }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.serviceAccount.roleArn }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
